### PR TITLE
Working Game - Tic-Tac-Toe

### PR DESCRIPTION
**Pull request by compilepeace**
Please don't merge the changes. This is a working game, we will remove snippets of code from it (probably functions) and create tasks accordingly. Please review the code.

### CODE REVIEW

**Comment by garg-anuj** [comment]
@compilepeace Please move code user a dir tic-tac-toe

**Comment by shubhamvashisht** [comment]
@compilepeace can you add a list of all the cpp apps/programs you are going to push into this repo. So that others can suggest some cool apps too.
discuss on gitter.

**Comment by compilepeace** [comment]
@garg-anuj I did'nt get you

**Comment by compilepeace** [comment]
@shubhamvashisht I am working on it, i will push it as soon as possible.

**Comment by compilepeace** [comment]
There are some bugs in this game too... which are going to be fixed

**Comment by garg-anuj** [comment]
@compilepeace create a directory named tic-tac-toe and move code of game to that directory

**Comment by compilepeace** [comment]
@garg-anuj okay

**Comment by compilepeace** [comment]
So, can we proceed with this project ?

**Comment by garg-anuj** [comment]
@compilepeace sure

**Pull request closed without merging**
